In [24]:
import numpy as np


In [5]:
data = np.random.randn(2,3)


In [6]:
data

array([[-0.65892802,  2.28826181, -0.31448031],
       [-0.41944   , -0.17080145, -0.61543152]])

In [7]:
data*10

array([[-6.58928017, 22.88261813, -3.14480314],
       [-4.19440004, -1.70801452, -6.1543152 ]])

In [8]:
data+data

array([[-1.31785603,  4.57652363, -0.62896063],
       [-0.83888001, -0.3416029 , -1.23086304]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
mylist = [10,12,14]
na = np.array(mylist)

In [12]:
na.ndim

1

In [13]:
na.shape

(3,)

In [14]:
na.dtype

dtype('int32')

In [15]:
list2 = [[1,2,3],[4,5,6]]

In [16]:
na2 = np.array(list2)

In [17]:
na2.shape

(2, 3)

In [18]:
na2.ndim

2

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1= np.array([1,2,3],dtype=np.float64)

In [26]:
arr1.dtype


dtype('float64')

In [28]:
arr2=np.array([1,2,3], dtype=np.int32)

In [29]:
arr2.dtype

dtype('int32')

In [30]:
uarr = arr2.astype(np.uint32)

In [31]:
uarr

array([1, 2, 3], dtype=uint32)