In [24]:
import numpy as np


In [5]:
data = np.random.randn(2,3)


In [6]:
data

array([[-0.65892802,  2.28826181, -0.31448031],
       [-0.41944   , -0.17080145, -0.61543152]])

In [7]:
data*10

array([[-6.58928017, 22.88261813, -3.14480314],
       [-4.19440004, -1.70801452, -6.1543152 ]])

In [8]:
data+data

array([[-1.31785603,  4.57652363, -0.62896063],
       [-0.83888001, -0.3416029 , -1.23086304]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
mylist = [10,12,14]
na = np.array(mylist)

In [12]:
na.ndim

1

In [13]:
na.shape

(3,)

In [14]:
na.dtype

dtype('int32')

In [15]:
list2 = [[1,2,3],[4,5,6]]

In [16]:
na2 = np.array(list2)

In [17]:
na2.shape

(2, 3)

In [18]:
na2.ndim

2

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1= np.array([1,2,3],dtype=np.float64)

In [26]:
arr1.dtype


dtype('float64')

In [28]:
arr2=np.array([1,2,3], dtype=np.int32)

In [29]:
arr2.dtype

dtype('int32')

In [30]:
uarr = arr2.astype(np.uint32)

In [31]:
uarr

array([1, 2, 3], dtype=uint32)

In [33]:
arr = np.arange(10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[9]

9

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[4:8]=10

In [42]:
arr

array([ 0,  1,  2,  3, 10, 10, 10, 10,  8,  9])

In [43]:
array = arr[3:7]

In [44]:
array[:]=5

In [45]:
arr

array([ 0,  1,  2,  5,  5,  5,  5, 10,  8,  9])

In [49]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [50]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr3d[0,1]

array([4, 5, 6])

In [55]:
arr3d[0,1][0:1]

array([4])

In [56]:
arr3d[0]=12


In [57]:
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arrcopy = arr3d[1].copy()


In [59]:
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arrcopy

array([[ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr3d[1]=0

In [62]:
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 0,  0,  0],
        [ 0,  0,  0]]])

In [63]:
arr3d[1]=arrcopy

In [64]:
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[1,0]

array([7, 8, 9])

In [68]:
names=np.array(['Bob','John', 'Tom', 'Tim','Bob', 'Lily', 'Lucy'])

In [69]:
names=='Bob'

array([ True, False, False, False,  True, False, False])

In [70]:
names

array(['Bob', 'John', 'Tom', 'Tim', 'Bob', 'Lily', 'Lucy'], dtype='<U4')

In [71]:
data= np.random.randn(7,4)


In [72]:
data


array([[ 0.39136311,  0.98641989, -0.82249722, -0.25866012],
       [ 1.27413158,  1.86817535, -0.00746835, -0.85226903],
       [ 0.88851397, -1.47408552, -0.46110615, -2.16510872],
       [-1.00207672, -0.64785852,  0.704393  ,  1.22068111],
       [-0.05384661,  0.26806149,  0.17627655, -0.3127856 ],
       [-1.12383401,  0.01098368, -0.44987906, -0.12308582],
       [-0.48571786, -1.12811121, -0.65705335,  1.10838195]])

In [73]:
data[names=='Bob']

array([[ 0.39136311,  0.98641989, -0.82249722, -0.25866012],
       [-0.05384661,  0.26806149,  0.17627655, -0.3127856 ]])

In [76]:
data[:, names=='Bob']

IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 7

In [77]:
data = np.random.randn(8,3)

In [81]:
data

array([[ 1.29187913e+00, -5.57035769e-01, -1.02732564e+00],
       [-2.21042332e+00, -1.45535840e-01,  1.09612731e+00],
       [ 5.91243870e-01,  9.37135004e-02,  5.68910398e-01],
       [-6.58326795e-01,  1.45162227e+00,  4.98061390e-01],
       [ 5.59525428e-01,  1.20897472e+00, -9.50337011e-04],
       [ 3.05066118e-01,  8.89148742e-01,  3.52684734e-01],
       [ 1.56145454e-01, -6.69491090e-01, -7.97011742e-01],
       [-3.61578010e-01,  5.72159247e-02, -1.27632330e+00]])

In [83]:
data[data<0]=0

In [84]:
data

array([[1.29187913, 0.        , 0.        ],
       [0.        , 0.        , 1.09612731],
       [0.59124387, 0.0937135 , 0.5689104 ],
       [0.        , 1.45162227, 0.49806139],
       [0.55952543, 1.20897472, 0.        ],
       [0.30506612, 0.88914874, 0.35268473],
       [0.15614545, 0.        , 0.        ],
       [0.        , 0.05721592, 0.        ]])