In [1]:
import pandas as pd

In [2]:
obj=pd.Series([3,5,6,7])

In [3]:
obj


0    3
1    5
2    6
3    7
dtype: int64

In [4]:
obj.values

array([3, 5, 6, 7], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2=pd.Series([1,2,3,4], index=['a','b','c','d'])

In [7]:
obj2


a    1
b    2
c    3
d    4
dtype: int64

In [8]:
obj2.values

array([1, 2, 3, 4], dtype=int64)

In [9]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
obj2['b']

2

In [15]:
obj2[['a','c','d']]

a    1
c    3
d    4
dtype: int64

In [19]:
import numpy as nd
obj2= nd.arange(10).reshape(2,5)

In [20]:
obj2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
obj2 = nd.random.randn(3,4)

In [23]:
obj2

array([[-0.46337829,  0.20703845, -0.04737812,  0.93830656],
       [ 1.26385261, -0.91598098, -0.35940143,  1.23825981],
       [ 1.51629339,  1.04801489,  1.23089782, -0.03539067]])

In [25]:
obj = {'lily':100, 'lucy':93, 'ketty':60 ,'tom':50}

In [26]:
obj2=pd.Series(obj)

In [27]:
obj2

lily     100
lucy      93
ketty     60
tom       50
dtype: int64

In [29]:
obj2[obj2>60]

lily    100
lucy     93
dtype: int64

In [30]:
obj2*2

lily     200
lucy     186
ketty    120
tom      100
dtype: int64

In [31]:
'lily' in obj2

True

In [32]:
'wen' in obj2

False

In [33]:
Astudent = ['lily', 'wen', 'tom']
obj2 = pd.Series(obj, index=Astudent)

In [34]:
obj2

lily    100.0
wen       NaN
tom      50.0
dtype: float64

In [35]:
pd.isnull(obj2)

lily    False
wen      True
tom     False
dtype: bool

In [36]:
obj2.isnull()

lily    False
wen      True
tom     False
dtype: bool

In [37]:
obj2.name='test'

In [38]:
obj2

lily    100.0
wen       NaN
tom      50.0
Name: test, dtype: float64

In [39]:
obj2.index.name='studentname'

In [41]:
obj2.index

Index(['lily', 'wen', 'tom'], dtype='object', name='studentname')

In [42]:
data = {'Lily':[100,98,50], 'tom':[99,60,100], 'lucy':[100,100,100]}

In [43]:
df = pd.DataFrame(data)

In [44]:
df

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [45]:
df.head()

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [46]:
pd.DataFrame(df, columns=['tom'])

tom
0   99
1   60
2  100

In [47]:
pd.DataFrame(df, index=['tom', 'wen'])

Lily  tom  lucy
tom   NaN  NaN   NaN
wen   NaN  NaN   NaN

In [49]:
pd.DataFrame(df, index=[0, 1])

Lily  tom  lucy
0   100   99   100
1    98   60   100

In [50]:
df['tom']

0     99
1     60
2    100
Name: tom, dtype: int64

In [51]:
df.tom

0     99
1     60
2    100
Name: tom, dtype: int64

In [52]:
df

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [53]:
df.Lily=100

In [54]:
df

Lily  tom  lucy
0   100   99   100
1   100   60   100
2   100  100   100

In [58]:
df.loc(1)

In [62]:
import numpy as np
df.tom = np.arange(3)

In [63]:
df

Lily  tom  lucy
0   100    0   100
1   100    1   100
2   100    2   100

In [64]:
df.index


RangeIndex(start=0, stop=3, step=1)

In [65]:
df.values

array([[100,   0, 100],
       [100,   1, 100],
       [100,   2, 100]], dtype=int64)

In [66]:
obj = pd.Series(range(3), index=['a','b','c'])

In [67]:
obj

a    0
b    1
c    2
dtype: int64

In [68]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [70]:
obj.index[:0]

Index([], dtype='object')

In [72]:
index = obj.index
index[1]='d'

TypeError: Index does not support mutable operations

In [73]:
dump_labels = pd.Index(['fool', 'fool', 'bus', 'car'])

In [74]:
dump_labels

Index(['fool', 'fool', 'bus', 'car'], dtype='object')

In [75]:
dump_labels.unique()

Index(['fool', 'bus', 'car'], dtype='object')

In [78]:
dump_labels.is_unique

False

In [80]:
dump_labels

Index(['fool', 'fool', 'bus', 'car'], dtype='object')

In [84]:
dump_labels.delete(1)

Index(['fool', 'bus', 'car'], dtype='object')

In [85]:
dump_labels

Index(['fool', 'fool', 'bus', 'car'], dtype='object')

In [87]:
speed = pd.DataFrame([100,100, 50, 80], index=dump_labels)

In [88]:
speed

0
fool  100
fool  100
bus    50
car    80

In [91]:
del speed.T['fool']

In [93]:
speed = speed.T

In [94]:
speed

fool  fool  bus  car
0   100   100   50   80

In [95]:
speed.reindex([0,1])

fool   fool   bus   car
0  100.0  100.0  50.0  80.0
1    NaN    NaN   NaN   NaN

In [99]:
speed.drop(['fool'], axis=1)

bus  car
0   50   80

In [100]:
speed = speed.reindex(['0', '1'])

In [101]:
speed

fool  fool  bus  car
0   NaN   NaN  NaN  NaN
1   NaN   NaN  NaN  NaN

In [102]:
speed.drop(['0'])

fool  fool  bus  car
1   NaN   NaN  NaN  NaN

In [103]:
speed

fool  fool  bus  car
0   NaN   NaN  NaN  NaN
1   NaN   NaN  NaN  NaN

In [104]:
speed = speed.reindex(range(5))

In [105]:
speed


fool  fool  bus  car
0   NaN   NaN  NaN  NaN
1   NaN   NaN  NaN  NaN
2   NaN   NaN  NaN  NaN
3   NaN   NaN  NaN  NaN
4   NaN   NaN  NaN  NaN

In [106]:
speed.drop([1])

fool  fool  bus  car
0   NaN   NaN  NaN  NaN
2   NaN   NaN  NaN  NaN
3   NaN   NaN  NaN  NaN
4   NaN   NaN  NaN  NaN

In [107]:
speed.index

RangeIndex(start=0, stop=5, step=1)

In [108]:
speed

fool  fool  bus  car
0   NaN   NaN  NaN  NaN
1   NaN   NaN  NaN  NaN
2   NaN   NaN  NaN  NaN
3   NaN   NaN  NaN  NaN
4   NaN   NaN  NaN  NaN

In [113]:
speed = speed.reindex(range(4,8))

In [114]:
speed

fool  fool  bus  car
4   NaN   NaN  NaN  NaN
5   NaN   NaN  NaN  NaN
6   NaN   NaN  NaN  NaN
7   NaN   NaN  NaN  NaN

In [118]:
speed.drop(speed.index[:2])

fool  fool  bus  car
6   NaN   NaN  NaN  NaN
7   NaN   NaN  NaN  NaN

In [119]:
speed


fool  fool  bus  car
4   NaN   NaN  NaN  NaN
5   NaN   NaN  NaN  NaN
6   NaN   NaN  NaN  NaN
7   NaN   NaN  NaN  NaN

In [120]:
speed['fool']=range(4)

In [121]:
speed


fool  fool  bus  car
4     0     0  NaN  NaN
5     1     1  NaN  NaN
6     2     2  NaN  NaN
7     3     3  NaN  NaN

In [122]:
speed['fool']

fool  fool
4     0     0
5     1     1
6     2     2
7     3     3

In [123]:
speed[0:2]

fool  fool  bus  car
4     0     0  NaN  NaN
5     1     1  NaN  NaN

In [124]:
speed[speed<2]

ValueError: cannot reindex from a duplicate axis

In [125]:
del speed['fool']

In [126]:
speed


bus  car
4  NaN  NaN
5  NaN  NaN
6  NaN  NaN
7  NaN  NaN

In [127]:
speed['bus']=np.random.randn(4)

In [128]:
speed['car']=np.random.randn(4
)

In [129]:
speed

bus       car
4 -0.449454 -0.235940
5  1.310540  0.386252
6 -0.705774 -0.402625
7  1.312618  1.318837

In [130]:
speed[speed>0]

bus       car
4       NaN       NaN
5  1.310540  0.386252
6       NaN       NaN
7  1.312618  1.318837

In [131]:
speed>0


bus    car
4  False  False
5   True   True
6  False  False
7   True   True

In [132]:
speed[:3]

bus       car
4 -0.449454 -0.235940
5  1.310540  0.386252
6 -0.705774 -0.402625

In [133]:
speed[4:5
    ]

Empty DataFrame
Columns: [bus, car]
Index: []

In [134]:
speed

bus       car
4 -0.449454 -0.235940
5  1.310540  0.386252
6 -0.705774 -0.402625
7  1.312618  1.318837

In [135]:
speed[4,5]=5


In [136]:
speed


bus       car  (4, 5)
4 -0.449454 -0.235940       5
5  1.310540  0.386252       5
6 -0.705774 -0.402625       5
7  1.312618  1.318837       5

In [138]:
speed[4]=5


In [139]:
speed


bus       car  (4, 5)  4
4 -0.449454 -0.235940       5  5
5  1.310540  0.386252       5  5
6 -0.705774 -0.402625       5  5
7  1.312618  1.318837       5  5

In [141]:
speed = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [142]:
speed

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [143]:
speed['a':'b']

a    0.0
b    1.0
dtype: float64

In [144]:
speed['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [147]:
speed([0:2])


SyntaxError: invalid syntax (<ipython-input-147-2db4bd7aba59>, line 1)

In [148]:
speed[0:2]

a    0.0
b    1.0
dtype: float64

In [150]:
speed = pd.DataFrame({'Tom':[100.,88,50], 'wen':[99,99,100], 'Lily':[60,69,60]})

In [151]:
speed

Tom  wen  Lily
0  100.0   99    60
1   88.0   99    69
2   50.0  100    60

In [158]:
speed.loc[[1,2], ['Lily', 'Tom', 'wen']]

Lily   Tom  wen
1    69  88.0   99
2    60  50.0  100

In [157]:
speed.loc[2]

Tom      50.0
wen     100.0
Lily     60.0
Name: 2, dtype: float64

In [166]:
ser = pd.Series(range(5))

In [167]:
ser

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [173]:

ser.iloc[-2:-1]

3    3
dtype: int64

In [162]:
ser = pd.Series(range(4), index=['a', 'b', 'c', 'd'])

In [163]:
ser

a    0
b    1
c    2
d    3
dtype: int64

In [165]:
ser[-1]

3

In [174]:
s1=pd.Series([2.3,3.34, 10.5], index=['a', 'b', 'c'])

In [176]:
s2=pd.Series([5.23, 4.5, 7.8], index=['b', 'd','e'])

s1

In [177]:
s2

b    5.23
d    4.50
e    7.80
dtype: float64

In [178]:
s1

a     2.30
b     3.34
c    10.50
dtype: float64

In [179]:
s1*s2

a        NaN
b    17.4682
c        NaN
d        NaN
e        NaN
dtype: float64

In [180]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3),columns=list('bcd'))

In [183]:
df2=pd.DataFrame(np.arange(12).reshape(4,3), columns=list('bde'))

In [184]:
df1


b  c  d
0  0  1  2
1  3  4  5
2  6  7  8

In [185]:
df2

b   d   e
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [186]:
df1+df2

b   c     d   e
0   0.0 NaN   3.0 NaN
1   6.0 NaN   9.0 NaN
2  12.0 NaN  15.0 NaN
3   NaN NaN   NaN NaN

In [187]:
df1*df2

b   c     d   e
0   0.0 NaN   2.0 NaN
1   9.0 NaN  20.0 NaN
2  36.0 NaN  56.0 NaN
3   NaN NaN   NaN NaN

In [188]:
df1.add(df2, fill_value=0)

b    c     d     e
0   0.0  1.0   3.0   2.0
1   6.0  4.0   9.0   5.0
2  12.0  7.0  15.0   8.0
3   9.0  NaN  10.0  11.0

In [190]:
df2.add(df1, fill_value=0)

b    c     d     e
0   0.0  1.0   3.0   2.0
1   6.0  4.0   9.0   5.0
2  12.0  7.0  15.0   8.0
3   9.0  NaN  10.0  11.0

In [193]:
frame = pd.DataFrame(np.arange(12).reshape(4,3), columns=list('bcd'), index=['tom', 'lily', 'john', 'bob'])

In [194]:
frame


b   c   d
tom   0   1   2
lily  3   4   5
john  6   7   8
bob   9  10  11

In [195]:
series = frame.iloc[1]

In [197]:
series



b    3
c    4
d    5
Name: lily, dtype: int32

In [198]:
frame-series

b  c  d
tom  -3 -3 -3
lily  0  0  0
john  3  3  3
bob   6  6  6

In [201]:
series = pd.Series(np.arange(4), index=['a', 'c', 'd', 'e'])

In [203]:
frame+series


a   b     c     d   e
tom  NaN NaN   2.0   4.0 NaN
lily NaN NaN   5.0   7.0 NaN
john NaN NaN   8.0  10.0 NaN
bob  NaN NaN  11.0  13.0 NaN

In [204]:
series


a    0
c    1
d    2
e    3
dtype: int32

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Mr Li', 'Miss Liu', 'Mr Sun', 'Miss Qin'])

In [3]:
df

b         d         e
Mr Li    -0.117546  0.169215 -0.432115
Miss Liu -0.004486 -0.801520 -0.769205
Mr Sun   -0.718977 -1.527381  0.328910
Miss Qin -0.399230 -0.352076  1.635827

In [4]:
np.abs(df)

b         d         e
Mr Li     0.117546  0.169215  0.432115
Miss Liu  0.004486  0.801520  0.769205
Mr Sun    0.718977  1.527381  0.328910
Miss Qin  0.399230  0.352076  1.635827

In [7]:
f = lambda x:x.max()-x.min()

In [8]:
df.apply(f)

b    0.714491
d    1.696595
e    2.405032
dtype: float64

In [14]:
df.index

Index(['Mr Li', 'Miss Liu', 'Mr Sun', 'Miss Qin'], dtype='object')

In [15]:
df.T.apply(f)

Mr Li       0.601330
Miss Liu    0.797034
Mr Sun      1.856291
Miss Qin    2.035057
dtype: float64

In [16]:
df.T

Mr Li  Miss Liu    Mr Sun  Miss Qin
b -0.117546 -0.004486 -0.718977 -0.399230
d  0.169215 -0.801520 -1.527381 -0.352076
e -0.432115 -0.769205  0.328910  1.635827

In [17]:
df

b         d         e
Mr Li    -0.117546  0.169215 -0.432115
Miss Liu -0.004486 -0.801520 -0.769205
Mr Sun   -0.718977 -1.527381  0.328910
Miss Qin -0.399230 -0.352076  1.635827

In [18]:
df.apply(f)

b    0.714491
d    1.696595
e    2.405032
dtype: float64

In [19]:
df.T.apply(f)

Mr Li       0.601330
Miss Liu    0.797034
Mr Sun      1.856291
Miss Qin    2.035057
dtype: float64

In [20]:
df.T

Mr Li  Miss Liu    Mr Sun  Miss Qin
b -0.117546 -0.004486 -0.718977 -0.399230
d  0.169215 -0.801520 -1.527381 -0.352076
e -0.432115 -0.769205  0.328910  1.635827

In [21]:
df

b         d         e
Mr Li    -0.117546  0.169215 -0.432115
Miss Liu -0.004486 -0.801520 -0.769205
Mr Sun   -0.718977 -1.527381  0.328910
Miss Qin -0.399230 -0.352076  1.635827

In [23]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', max])

In [24]:
df.apply(f)

b         d         e
min                     -0.718977 -1.527381 -0.769205
<built-in function max> -0.004486  0.169215  1.635827

In [26]:
format = lambda x:'%.2f' % x

In [27]:
df

b         d         e
Mr Li    -0.117546  0.169215 -0.432115
Miss Liu -0.004486 -0.801520 -0.769205
Mr Sun   -0.718977 -1.527381  0.328910
Miss Qin -0.399230 -0.352076  1.635827

In [30]:
df.applymap(format)

b      d      e
Mr Li     -0.12   0.17  -0.43
Miss Liu  -0.00  -0.80  -0.77
Mr Sun    -0.72  -1.53   0.33
Miss Qin  -0.40  -0.35   1.64

In [31]:
series = pd.Series(range(4), index=['c', 'b', 'a', 'd'])

In [32]:
series

c    0
b    1
a    2
d    3
dtype: int64

In [33]:
series.sort_index()

a    2
b    1
c    0
d    3
dtype: int64

In [35]:
series.sort_values()

c    0
b    1
a    2
d    3
dtype: int64

In [36]:
series['d']=NaN

NameError: name 'NaN' is not defined

In [39]:
series =series.reindex(['a','b', 'c','d', 'e'])

In [40]:
series

a    2.0
b    1.0
c    0.0
d    3.0
e    NaN
dtype: float64

In [42]:
series.sort_values(ascending=False)

d    3.0
a    2.0
b    1.0
c    0.0
e    NaN
dtype: float64

In [43]:
series.sort_values(ascending=True)

c    0.0
b    1.0
a    2.0
d    3.0
e    NaN
dtype: float64

In [45]:
df=pd.DataFrame({'b':[4,7, -3, 2], 'c':[8,9,2,20]})

In [46]:
df

b   c
0  4   8
1  7   9
2 -3   2
3  2  20

In [50]:
df.sort_values(by='c',ascending=False)

b   c
3  2  20
1  7   9
0  4   8
2 -3   2

In [51]:
df

b   c
0  4   8
1  7   9
2 -3   2
3  2  20

In [53]:
df.rank()

b    c
0  3.0  2.0
1  4.0  3.0
2  1.0  1.0
3  2.0  4.0

In [56]:
df.rank(ascending=False,method='max')

b    c
0  2.0  3.0
1  1.0  2.0
2  4.0  4.0
3  3.0  1.0

In [57]:
df.rank(ascending=False)

b    c
0  2.0  3.0
1  1.0  2.0
2  4.0  4.0
3  3.0  1.0

In [59]:
df.rank(axis='index')

b    c
0  3.0  2.0
1  4.0  3.0
2  1.0  1.0
3  2.0  4.0

In [60]:
df

b   c
0  4   8
1  7   9
2 -3   2
3  2  20

In [61]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [62]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [63]:
obj['a']

a    0
a    1
dtype: int64

In [65]:
obj.index.is_unique

False

In [66]:
obj['c']

4

In [67]:
obj.sum()

10

In [68]:
df

b   c
0  4   8
1  7   9
2 -3   2
3  2  20

In [69]:
df.sum()

b    10
c    39
dtype: int64

In [70]:
df.sum(axis='columns')

0    12
1    16
2    -1
3    22
dtype: int64

In [75]:
df.sum(axis=0)

b    10
c    39
dtype: int64

In [77]:
df.idxmax()

b    1
c    3
dtype: int64

In [78]:
df.idxmin()

b    2
c    2
dtype: int64

In [79]:
df.cumsum()

b   c
0   4   8
1  11  17
2   8  19
3  10  39

In [80]:
df

b   c
0  4   8
1  7   9
2 -3   2
3  2  20

In [81]:
df.describe()

b      c
count  4.000000   4.00
mean   2.500000   9.75
std    4.203173   7.50
min   -3.000000   2.00
25%    0.750000   6.50
50%    3.000000   8.50
75%    4.750000  11.75
max    7.000000  20.00

In [83]:
df['b'].unique()

array([ 4,  7, -3,  2], dtype=int64)

In [84]:
df['e']='2'

In [85]:
df

b   c  e
0  4   8  2
1  7   9  2
2 -3   2  2
3  2  20  2

In [86]:
df['e'].unique()

array(['2'], dtype=object)

In [92]:
pd.value_counts(df['c'].values)

20    1
2     1
9     1
8     1
dtype: int64

In [94]:
to_match = pd.Series(['c', 'a','c','b','e'])

In [95]:
unique_vals = pd.Series(['c', 'a', 'b'])

In [96]:
pd.Index(unique_vals).get_indexer(to_match)

array([ 0,  1,  0,  2, -1], dtype=int64)