In [1]:
import pandas as pd

In [2]:
obj=pd.Series([3,5,6,7])

In [3]:
obj


0    3
1    5
2    6
3    7
dtype: int64

In [4]:
obj.values

array([3, 5, 6, 7], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2=pd.Series([1,2,3,4], index=['a','b','c','d'])

In [7]:
obj2


a    1
b    2
c    3
d    4
dtype: int64

In [8]:
obj2.values

array([1, 2, 3, 4], dtype=int64)

In [9]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
obj2['b']

2

In [15]:
obj2[['a','c','d']]

a    1
c    3
d    4
dtype: int64

In [19]:
import numpy as nd
obj2= nd.arange(10).reshape(2,5)

In [20]:
obj2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
obj2 = nd.random.randn(3,4)

In [23]:
obj2

array([[-0.46337829,  0.20703845, -0.04737812,  0.93830656],
       [ 1.26385261, -0.91598098, -0.35940143,  1.23825981],
       [ 1.51629339,  1.04801489,  1.23089782, -0.03539067]])

In [25]:
obj = {'lily':100, 'lucy':93, 'ketty':60 ,'tom':50}

In [26]:
obj2=pd.Series(obj)

In [27]:
obj2

lily     100
lucy      93
ketty     60
tom       50
dtype: int64

In [29]:
obj2[obj2>60]

lily    100
lucy     93
dtype: int64

In [30]:
obj2*2

lily     200
lucy     186
ketty    120
tom      100
dtype: int64

In [31]:
'lily' in obj2

True

In [32]:
'wen' in obj2

False

In [33]:
Astudent = ['lily', 'wen', 'tom']
obj2 = pd.Series(obj, index=Astudent)

In [34]:
obj2

lily    100.0
wen       NaN
tom      50.0
dtype: float64

In [35]:
pd.isnull(obj2)

lily    False
wen      True
tom     False
dtype: bool

In [36]:
obj2.isnull()

lily    False
wen      True
tom     False
dtype: bool

In [37]:
obj2.name='test'

In [38]:
obj2

lily    100.0
wen       NaN
tom      50.0
Name: test, dtype: float64

In [39]:
obj2.index.name='studentname'

In [41]:
obj2.index

Index(['lily', 'wen', 'tom'], dtype='object', name='studentname')

In [42]:
data = {'Lily':[100,98,50], 'tom':[99,60,100], 'lucy':[100,100,100]}

In [43]:
df = pd.DataFrame(data)

In [44]:
df

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [45]:
df.head()

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [46]:
pd.DataFrame(df, columns=['tom'])

tom
0   99
1   60
2  100

In [47]:
pd.DataFrame(df, index=['tom', 'wen'])

Lily  tom  lucy
tom   NaN  NaN   NaN
wen   NaN  NaN   NaN

In [49]:
pd.DataFrame(df, index=[0, 1])

Lily  tom  lucy
0   100   99   100
1    98   60   100

In [50]:
df['tom']

0     99
1     60
2    100
Name: tom, dtype: int64

In [51]:
df.tom

0     99
1     60
2    100
Name: tom, dtype: int64

In [52]:
df

Lily  tom  lucy
0   100   99   100
1    98   60   100
2    50  100   100

In [53]:
df.Lily=100

In [54]:
df

Lily  tom  lucy
0   100   99   100
1   100   60   100
2   100  100   100

In [58]:
df.loc(1)

In [62]:
import numpy as np
df.tom = np.arange(3)

In [63]:
df

Lily  tom  lucy
0   100    0   100
1   100    1   100
2   100    2   100